name: EBS record
description: 'Record EBS english radio'
jobs:
  record:
    runs-on: ubuntu-20.04
    steps:  
      - uses: actions/checkout@v3
      - name: Run!      
        run: |        
          export TOKEN=$BOT_TELEGRAM_TOKEN
          export CHAT_ID=$CHAT_ID
          sudo apt install ffmpeg
          sh ebs.sh MouseEnglish 19
        env:
            BOT_TELEGRAM_TOKEN: ${{ secrets.BOT_TELEGRAM_TOKEN }} 
            CHAT_ID: ${{ secrets.CHAT_ID }}
branding:
  icon: radio
  color: green
